spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop   # :MVCC=TRUE 옵션은 업데이트 이후 사라짐
    # jdbc:h2:mem:test h2를 꺼도 작동되는 메모리 모드로 url 설정
    # jdbc:h2:tcp://localhost/~/jpashop tcp로 접속하는 url 설정
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      # create, create-drop 엔티티를 모두 크리에이트 해주고 마지막에 드랍까지
    properties:
      hibernate:
#       show_sql: true // system.out에 출력
        format_sql: true

# 심지어 spring boot에서는 이 설정정보가 없으면 기본적으로 메모리모드로 db를 돌리기 때문에
# 위에 코드들을 주석처리해도 작동이 된다.

logging:
  level:
    org.hibernate.SQL: debug # logger를 통해 출력 (권장)
    org.hibernate.type: trace